name: auto_service-backend

services:
  backend:
    container_name: backend
    build: backend
    restart: always
    env_file: .env
    depends_on:
      - database
    ports:
      - 8100:8000

  frontend:
    container_name: frontend
    build: frontend
    restart: always
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8101:3000

  database:
    container_name: database
    restart: always
    image: postgres:latest
    env_file: .env
    volumes:
      - ./dumps/testing.sql:/docker-entrypoint-initdb.d/testing.sql
    # ports:
    #   - 5432:5432

