"""empty message

Revision ID: 5961388882f1
Revises: d53f24144ac1
Create Date: 2024-12-13 02:54:48.530632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5961388882f1'
down_revision: Union[str, None] = 'd53f24144ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint('posts_channel_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_channel_id_fkey', 'posts', 'posts', ['channel_id'], ['id'])
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###
